"""
Build species metadata for plant ID reranking (Phase 2).

Reads the plant_classes.json generated by build_plant_dataset.py and queries
iNaturalist for each species to build metadata records with region,
season, and plant-part information.

Usage:
  python tools/build_plant_metadata.py

Output:
  assets/models/plant_metadata.json

Requires: pip install requests
"""

import json
import os
import sys
from pathlib import Path

# Common names and known-toxic flags for priority species.
# The script also attempts to fetch common names from iNaturalist.
KNOWN_METADATA = {
    "Toxicodendron radicans": {"common_name": "Poison Ivy", "toxic": True},
    "Toxicodendron vernix": {"common_name": "Poison Sumac", "toxic": True},
    "Conium maculatum": {"common_name": "Poison Hemlock", "toxic": True},
    "Cicuta maculata": {"common_name": "Water Hemlock", "toxic": True},
    "Atropa belladonna": {"common_name": "Deadly Nightshade", "toxic": True},
    "Datura stramonium": {"common_name": "Jimsonweed", "toxic": True},
    "Phytolacca americana": {"common_name": "Pokeweed", "toxic": True},
    "Actaea pachypoda": {"common_name": "White Baneberry", "toxic": True},
    "Arisaema triphyllum": {"common_name": "Jack-in-the-Pulpit", "toxic": True},
}

# US state / CA province bounding boxes for mapping coordinates to regions.
# Duplicated from the Dart region_lookup.dart — keep in sync.
STATE_ABBREVS = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    # Canadian provinces
    "Alberta": "AB",
    "British Columbia": "BC",
    "Manitoba": "MB",
    "New Brunswick": "NB",
    "Newfoundland and Labrador": "NL",
    "Nova Scotia": "NS",
    "Northwest Territories": "NT",
    "Nunavut": "NU",
    "Ontario": "ON",
    "Prince Edward Island": "PE",
    "Quebec": "QC",
    "Saskatchewan": "SK",
    "Yukon": "YT",
}


def fetch_taxon_info(species_name):
    """Fetch taxon details from iNaturalist API."""
    try:
        import requests
    except ImportError:
        os.system(f"{sys.executable} -m pip install requests")
        import requests

    url = "https://api.inaturalist.org/v1/taxa"
    resp = requests.get(
        url, params={"q": species_name, "rank": "species", "per_page": 1}, timeout=15
    )
    resp.raise_for_status()
    results = resp.json().get("results", [])
    if not results:
        return None
    return results[0]


def fetch_observation_stats(taxon_id, place_ids="6712,97394"):
    """
    Fetch month histogram and place observations for a taxon.
    Returns (month_counts, region_codes).
    """
    try:
        import requests
    except ImportError:
        os.system(f"{sys.executable} -m pip install requests")
        import requests

    # Month histogram
    url = f"https://api.inaturalist.org/v1/observations/histogram"
    params = {
        "taxon_id": taxon_id,
        "place_id": place_ids,
        "date_field": "observed",
        "interval": "month_of_year",
    }
    resp = requests.get(url, params=params, timeout=15)
    resp.raise_for_status()
    month_data = resp.json().get("results", {}).get("month_of_year", {})

    # Determine active months (months with >10% of peak observations)
    if month_data:
        values = {int(k): v for k, v in month_data.items()}
        peak = max(values.values()) if values else 0
        threshold = peak * 0.1
        active_months = sorted([m for m, c in values.items() if c >= threshold])
    else:
        active_months = list(range(1, 13))  # year-round if unknown

    return active_months


def infer_common_parts(taxon_info):
    """Infer which plant parts are useful for ID based on taxon ancestry."""
    parts = ["leaf", "wholePlant"]  # defaults

    # Check taxon ancestry for clues
    ancestors = [a.get("name", "") for a in taxon_info.get("ancestors", [])]
    name = taxon_info.get("name", "").lower()

    # Trees and shrubs: bark is useful
    tree_families = [
        "Pinaceae",
        "Fagaceae",
        "Betulaceae",
        "Juglandaceae",
        "Aceraceae",
        "Sapindaceae",
        "Oleaceae",
        "Ulmaceae",
    ]
    if any(f in ancestors for f in tree_families):
        parts.append("bark")

    # Flowering plants: flower is very useful
    if "Magnoliopsida" in ancestors or "Liliopsida" in ancestors:
        parts.append("flower")

    # Berry / fruit producers
    fruit_genera = [
        "rubus",
        "vaccinium",
        "sambucus",
        "viburnum",
        "ilex",
        "prunus",
        "malus",
        "gaultheria",
    ]
    if any(g in name for g in fruit_genera):
        parts.append("fruit")

    return list(set(parts))


def main():
    assets_dir = Path(__file__).parent.parent / "assets" / "models"
    class_file = assets_dir / "plant_classes.json"
    meta_file = assets_dir / "plant_metadata.json"

    if not class_file.exists():
        print(f"ERROR: {class_file} not found. Run build_plant_dataset.py first.")
        sys.exit(1)

    with open(class_file) as f:
        class_map = json.load(f)

    print(f"Building metadata for {len(class_map)} species...\n")

    metadata = []

    for class_id_str, species_name in class_map.items():
        class_id = int(class_id_str)
        print(
            f"[{class_id + 1}/{len(class_map)}] {species_name}...", end=" ", flush=True
        )

        # Fetch taxon info
        try:
            taxon = fetch_taxon_info(species_name)
        except Exception as e:
            print(f"WARN (taxon fetch: {e})")
            taxon = None

        # Common name
        known = KNOWN_METADATA.get(species_name, {})
        common_name = known.get("common_name")
        if not common_name and taxon:
            common_name = taxon.get("preferred_common_name", "")
        if not common_name:
            # Fall back to formatted scientific name
            common_name = species_name

        # Toxic flag
        toxic = known.get("toxic", False)

        # Active months
        active_months = list(range(1, 13))
        if taxon:
            try:
                active_months = fetch_observation_stats(taxon["id"])
            except Exception:
                pass

        # Common plant parts
        common_parts = ["leaf", "wholePlant"]
        if taxon:
            try:
                common_parts = infer_common_parts(taxon)
            except Exception:
                pass

        # Regions — we'll set broad US+Canada regions as default
        # A more precise approach would query observation places per species
        regions = []
        if taxon:
            # Use conservation status places or default to broad
            # For now, mark as present in all US+CA (refined in future)
            regions = list(STATE_ABBREVS.values())

        entry = {
            "class_id": class_id,
            "scientific_name": species_name,
            "common_name": common_name,
            "regions": regions,
            "active_months": active_months,
            "common_parts": common_parts,
            "toxic": toxic,
        }
        metadata.append(entry)
        print(f"OK ({common_name})")

    # Write metadata
    with open(meta_file, "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"\n{'='*60}")
    print(f"Metadata for {len(metadata)} species saved to: {meta_file}")
    toxic_count = sum(1 for m in metadata if m["toxic"])
    print(f"Toxic species flagged: {toxic_count}")


if __name__ == "__main__":
    main()
